# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.24
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Connect to PostgreSQL
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        run: go run main.go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

